name: IBM WebSphere Traditional®
version: 0.3.2
description: tWAS & OpenJ9 using Maven
license: Apache-2.0
language: java
maintainers:
  - name: Glenn Marcy
    email: gmarcy@us.ibm.com
    github-id: gmarcy
default-template: default
requirements:
    appsody-version: ">= 0.5.0"
    docker-version: ">= 17.09.0"
templating-data:
    twasversion: '9.0.5.3'
    epelrpm: 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm'
    jdkversion: 'jdk8u242-b08_openj9-0.18.1'
    jdksuffix: '8u242b08_openj9-0.18.1'
    jdkshappc64le: 'd958da86425c23c49a23dbe2616de55e6b44a2139c548880440505401ff48ec4'
    jdkshas390x: '82f34d0917c068e49cd23a7350ccc592648b31bad45ea89536577493a043eab6'
    jdkshax64: 'ca785af638b24f9d4df896f5a9f557cc9f1e5fa5e2b1174d6b906e3fd5474c2e'
    jdkdownload: 'https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download'
    baseimage: adoptopenjdk/openjdk8-openj9:jdk8u242-b08_openj9-0.18.1-ubi
    mavenversion: '3.6.3'
    mavensha: 'c35a1803a6e70a126e80b2b3ae33eed961f83ed74d18fcd16909b2d44d7dada3203f1ffe726c17ef8dcca2dcaa9fca676987befeadc9b9f759967a8cb77181c0'
    mavendownload: 'https://archive.apache.org/dist/maven/maven-3'
    finalimage: ibmcom/websphere-traditional:9.0.5.3-ubi
    parentpomgroup: dev.appsody
    parentpomid: java-websphere-traditional
    parentpomrange: '[0.3, 0.4)'
    parentpomfilename: appsody-twas-pom.xml
