apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata: 
  name: APPSODY_PROJECT_NAME
spec:
  version: 0.2.1
  applicationImage: APPSODY_DOCKER_IMAGE
  stack: APPSODY_STACK
  service:
    type: NodePort
    port: APPSODY_PORT
  expose: true
